const emission = {
  "Aerated concrete, autoclaved block, non-reinforced, for exterior walls": 0.43,
  "Aerated concrete, autoclaved block, non-reinforced, for interior walls": 0.41,
  "Aerated concrete, autoclaved, reinforced floor and wall element": 0.42,
  "Aerated concrete, autoclaved, reinforced intel": 0.48,
  "Gravel and sand": 0.005,
  "Air exchanger with heat recovery": 4.2,
  "Aluminium foil, scrap 0%": 14,
  "Aluminium profile, scrap 100%": 2,
  "Aluminium profile, scrap min 75%": 3.1,
  "Aluminium profile, tube, rod, extruded, scrap 0%": 7.2,
  "Aluminium sheet for walls and ceilings, scrap 0%": 12,
  "Bathroom full height cabinet": 1.4,
  "Bathroom mirror cabinet": 1.7,
  "Bathroom sink cabinet": 1.9,
  "Bathroom faucet": 6.8,
  "Bitumen waterproofing membrane, bottom layer TL2/TL3": 0.82,
  "Bitumen waterproofing membrane, continuous roofing system": 0.64,
  "Bitumen waterproofing membrane, roofing shingle": 0.48,
  "Bitumen waterproofing membrane, single-ply roofing system TL1": 0.78,
  "Bitumen waterproofing membrane, top layer membrane TL2": 0.67,
  "Asphalt concrete": 0.06,
  "Asphalt concrete for base courses": 0.06,
  "Brick, light": 0.28,
  "Brick, red": 0.22,
  "Accommodation / hotel": 79,
  "Apartment building": 42,
  "Cooling system for apartment buildings" : 1,
  "Cooling system for educational buildings" : 2,
  "Educational building": 61,
  "Fire extinguishing system, sprinkler (for apartment building)": 4,
  "Office": 66,
  "Other retail building": 47,
  "Shopping centre": 70,
  "Calcium silicate brick": 0.16,
  "Cellulose insulation board": 1.02,
  "Cellulose insulation, loose-fill": 0.108,
  "Ceramic tile for floors": 0.66,
  "Ceramic tile for walls": 0.77,
  "Chimney element, steel": 4.1,
  "Chipboard": 0.47,
  "Chipboard, melamine coated": 0.66,
  "CLT, Cross laminated timber": 0.2,
  "Concrete block, lightweight aggregates, insulated, U 0.17 W/m2K": 0.48,
  "Concrete block, lightweight aggregates, not insulated": 0.36,
  "Concrete block, insulated, U 0.17 W/m2K": 0.35,
  "Concrete cavity block": 0.19,
  "Concrete paving block": 0.16,
  "Concrete pile RTB-250": 0.2,
  "Concrete pile RTB-300": 0.19,
  "Concrete pile RTB-350": 0.2,
  "Concrete pipe 1200 Br": 0.19,
  "Concrete pipe 1200 Dr": 0.2,
  "Concrete pipe 600 Dr": 0.18,
  "Concrete pipe without reinforcement": 0.18,
  "Concrete roofing tile": 0.16,
  "Concrete well element Cr 2000": 0.18,
  "Concrete well element Cr 800": 0.18,
  "Copper sheet": 0.6,
  "Copper tube": 0.78,
  "Copper wire": 5,
  "Energy, district cooling": 0.042,
  "Energy, district heating": 0.147,
  "Door, indoor flush door": 1.6,
  "Door, metallic, fire-rated": 3.5,
  "Door, outdoor, glass with aluminium frame": 4,
  "Door, outdoor, wooden with steel frame": 1.5,
  "Door, outdoor, wooden with wooden frame": 0.78,
  "Electric cable protecting pipe, PVC": 2.4,
  "Electrical cable, low voltage": 5,
  "Electrical group center": 2.8,
  "Energy, electricity consumption": 0.153,
  "Passenger elevator": 3.6,
  "Energy, biofuels, decentralized heating": 0.027,
  "Energy, fossil fuels, decentralized heating": 0.306,
  "EPS insulation": 3.5,
  "Exhaust ventilation system": 3.5,
  "Expanded clay crushed aggregate": 0.4,
  "Fibre cement board": 1.15,
  "Fibreboard, hard": 0.25,
  "Fibreboard, medium density, mdf": 0.6,
  "Fibreboard, medium density, mdf, melamine coated": 0.96,
  "Fibreboard, soft, impregnated": 0.36,
  "Floor screed": 0.28,
  "Flooring, parquet": 0.94,
  "Flooring, polyamide textile": 6.5,
  "Flooring, vinyl flooring, PVC-based": 2.4,
  "Foamed glass crushed aggregate": 0.36,
  "Geotextile, PP-based": 1.9,
  "Glass tile": 2.7,
  "Acoustic panel, glass wool 20 mm, sound absorption class A": 1.4,
  "Acoustic panel, glass wool insulation 40 mm, sound absorption class A": 1.3,
  "Glass wool insulation, blowing": 1.08,
  "Glass wool insulation, density 100 kg/m3": 1.2,
  "Glass wool insulation, density 20 kg/m3": 1.2,
  "Glass wool insulation, density 60 kg/m3": 1.2,
  "Glass-aluminium facade, triple-glazed": 4,
  "Coated glass": 1.6,
  "Float glass": 1.4,
  "Insulating glass unit": 2,
  "Laminated glass": 2.1,
  "Mirror glass": 2,
  "Thermally toughened glass": 1.9,
  "GLT, Glued laminated timber": 0.13,
  "GLVL, multiple glued laminated veneer lumber": 0.41,
  "Gypsum plasterboard for interior use": 0.31,
  "Gypsum plasterboard, hard, fire resistant": 0.28,
  "Gypsum plasterboard, wind shield": 0.35,
  "Heat distribution pipe, PEX": 3.1,
  "Heat pump, air to air": 20,
  "Heat treated planed timber for indoor use": 1.2,
  "Heat treated planed timber for outdoor use": 1.2,
  "Heat treated timber for indoor use": 0.9,
  "Heat treated timber for outdoor use": 0.9,
  "Impregnated timber": 0.17,
  "Kitchen wall cabinet": 1.6,
  "Kitchen faucet with dishwasher valve": 6.9,
  "Kitchen lower cabinet": 1.6,
  "Kitchen sink": 4,
  "Laminated log wall structure": 0.2,
  "Luminaire, LED": 8.5,
  "LVL, laminated veneer lumber for beams, posts, and panels": 0.36,
  "LVL, laminated veneer lumber for wall studs": 0.36,
  "Metal connections for foundation piles, pile joints and rock point": 3.6,
  "Masonry mortar": 0.14,
  "Natural stone, solid curb stone": 0.12,
  "Natural stone for facades and floors": 0.37,
  "Natural stone, rectangular paving stone": 0.06,
  "Natural stone, slate for facades and yard": 0.035,
  "OSB panel": 0.42,
  "Paint, acrylic, water-borne for exterior use": 3,
  "Paint, acrylic, water-borne for interior use": 2.6,
  "Paint, epoxy-based for interior use for floors": 4.9,
  "Paint, silicate paint for mineral surface": 1.4,
  "Partition wall, glass with aluminium frame": 3,
  "Partition wall, glass with wooden frame": 2.2,
  "Phenolic insulation, aluminum foil coating, 20mm": 4.5,
  "Phenolic insulation, aluminum foil coating, 40-200mm": 2.8,
  "Phenolic insulation, glass tissue coating, 20mm": 2.8,
  "Phenolic insulation, glass tissue coating, 80-220mm": 2.5,
  "PIR-insulation": 4.2,
  "Plastering mortar": 0.29,
  "Plywood, birch, coated": 0.66,
  "Plywood, birch, uncoated": 0.48,
  "Plywood, spruce, coated": 0.48,
  "Plywood, spruce, uncoated": 0.36,
  "Precast concrete, solid slab element 220 mm": 0.19,
  "Precast concrete, solid slab element 280 mm": 0.19,
  "Precast concrete, beam 480 x 380 mm": 0.22,
  "Precast concrete, beam 580 x 380 mm": 0.22,
  "Precast concrete, beam 680 x 380 mm": 0.22,
  "Precast concrete, beam 780 x 480 mm": 0.22,
  "Precast concrete, column 280 x 280 mm": 0.23,
  "Precast concrete, column 380 x 380 mm": 0.23,
  "Precast concrete, column 480 x 480 mm": 0.23,
  "Precast concrete, column 580 x 580 mm": 0.23,
  "Precast concrete, hollow core slab 320 mm": 0.18,
  "Precast concrete, hollow core slab 200 mm": 0.18,
  "Precast concrete, hollow core slab 370 mm": 0.18,
  "Precast concrete, hollow core slab 400 mm": 0.18,
  "Precast concrete, hollow core slab 500 mm": 0.18,
  "Precast concrete, inner wall 150, insulation 140 mm": 0.22,
  "Precast concrete, inner wall 180, insulation 140 mm": 0.2,
  "Precast concrete, inner wall 200, insulation 140 mm": 0.19,
  "Precast concrete, partition wall 200 mm": 0.17,
  "Precast concrete, partition wall element 150 mm": 0.17,
  "Precast concrete, partition wall element 250 mm": 0.17,
  "Precast concrete, prestressed beam": 0.24,
  "Precast concrete, ribbed floor, TT-slab C50/60": 0.23,
  "Precast concrete, sandwich 80+220+80 mm": 0.28,
  "Precast concrete, sandwich, inner wall 150+220+80 mm": 0.25,
  "Precast concrete, solid slab 260 mm": 0.19,
  "Precast concrete, solid balcony slab 240 mm, C30/37": 0.18,
  "Precast concrete, hollow core slab 265 mm": 0.18,
  "Earthwork": 7,
  "Construction, office building": 78,
  "Construction, residential building": 46,
  "Construction, school or kindergarten": 60,
  "Stabilization": 0.04,
  "Demolition, office building": 14,
  "Demolition, residential building": 7,
  "Demolition, school or kindergarten": 9.8,
  "Waste disposal": 0.057,
  "Waste processing, metal materials": 0.002,
  "Waste processing, wooden materials": 0.02,
  "Transportation of building materials (m2)": 27,
  "Transport, bulk carrier, medium": 0.014,
  "Transport, container ship, 1 000 TEU": 0.045,
  "Transport, container train, diesel": 0.022,
  "Transport, earth moving truck, 40% load, highway": 0.1,
  "Transport, earth moving truck, 40% load, urban": 0.17,
  "Transport, earth moving truck, 50% load, highway": 0.085,
  "Transport, earth moving truck, 50% load, urban": 0.14,
  "Transport, heavy delivery lorry, 40 % load, highway": 0.14,
  "Transport, heavy delivery lorry, 40 % load, urban": 0.19,
  "Transport, heavy delivery lorry, 50 % load, highway": 0.11,
  "Transport, heavy delivery lorry, 50 % load, urban": 0.16,
  "Transport, semi-trailer, 40 % load, highway": 0.094,
  "Transport, semi-trailer, 40 % load, urban": 0.15,
  "Transport, semi-trailer, 50 % load, highway": 0.079,
  "Transport, semi-trailer, 50 % load, urban": 0.13,
  "Radiator, water circuit": 4.2,
  "Ready-mix concrete, C20/25, non-porous": 0.106,
  "Ready-mix concrete C20/25, non-porous, GWP.70": 0.073,
  "Ready-mix concrete C25/30, non-porous": 0.115,
  "Ready-mix concrete, C30/37, non-porous": 0.13,
  "Ready-mix concrete C30/37, porous": 0.15,
  "Crushed rock": 0.007,
  "Sandwich panel, steel, mineral wool insulation": 2.4,
  "Sandwich panel, steel, PIR insulation": 3.1,
  "Sawn timber": 0.083,
  "Sawn timber, planed": 0.088,
  "Shower faucet with shower set": 4.9,
  "Solar panel, monocrystalline": 23,
  "Solar thermal collector, flat plate": 5.2,
  "Sprinkler system, pipes": 3.1,
  "Stabilizer, cement": 0.36,
  "Stabilizer, Lime -cement, KC30 for harder soil, KC30": 0.95,
  "Stabilizer, lime -cement, KC50 general": 1.1,
  "Stabilizer, lime -cement with secondary raw material, POZ": 0.73,
  "Stabilizer, lime-cement-gypsum with secondary raw material, for problematic soil": 0.29,
  "Stainless steel rebar": 4.6,
  "Stainless steel sheet": 4.1,
  "Stainless steel tube": 4.3,
  "Staircase, wooden": 0.89,
  "Steel structure, load bearing truss, beam, column, pile, made of structural tube and section, coated or COR-TEN surface": 3,
  "Steel profile and grill, light-weight, galvanized": 2.8,
  "Steel rebar for concrete reinforcement": 0.67,
  "Steel sheet for roofing and cladding, hot-dip galvanized, painted or not-painted, or with COR-TEN surface": 3.1,
  "Steel, wire for concrete reinforcement": 1.2,
  "Acoustic panel, stone wool, Edge A, E": 1.9,
  "Acoustic panel, stone wool, Edge B, C, D": 1.7,
  "Stone wool insulation, blowing, average density 33 kg/m3": 1.5,
  "Stone wool insulation for facades, density 61 kg/m3": 1.5,
  "Stone wool, low-density for general building insulation, average density 29,5 kg/m3": 1.5,
  "Stone wool insulation for roofs, density 63 kg/m3": 1.5,
  "Toilet seat": 4.5,
  "Ventilation duct, metal": 3.1,
  "Washbasin": 3.6,
  "Waste processing, bricks and lime sand bricks": 0.005,
  "Waste processing, concrete materials": 0.006,
  "Waste processing, glass": 0.02,
  "Waste processing, gypsum (landfilling)": 0.0002,
  "Waste processing, gypsum (recycling)": 0.004,
  "Waste processing, plastics (energy recovery)": 3,
  "Waste processing, plastics (recycling)": 0.7,
  "Drinking water pipe, PEX": 3.8,
  "Water pump": 7,
  "Water vapour barrier, PE": 2.6,
  "Window, wood-aluminium, triple-glazed": 3.4,
  "XPS-insulation": 3.1,
  "Asphalt concrete (SMA)": 0.06,
  "Asphalt concrete (PAB)": 0.06,
  "Asphalt concrete (VA)": 0.06,
  "Asphalt concrete (AA)": 0.06,
  "Ready-mix concrete, C35/45, non-porous": 0.14,
  "Ready-mix concrete, C45/55, non-porous": 0.16,
  "Ready-mix concrete, C50/60, non-porous": 0.17,
  "Ready-mix concrete, C35/45, porous": 0.18,
  "Ready-mix concrete, C45/55, porous": 0.2,
  "Ready-mix concrete, C50/60, porous": 0.2,
  "Ready-mix concrete, C35/45, non-porous, GWP.70": 0.1,
  "Ready-mix concrete, C45/55, non-porous, GWP.70": 0.113,
  "Ready-mix concrete, C50/60, non-porous, GWP.70": 0.12,
  "Ready-mix concrete, C35/45, porous, GWP.70": 0.12,
  "Ready-mix concrete, C45/55, porous, GWP.70": 0.14,
  "Ready-mix concrete, C50/60, porous, GWP.70": 0.14,
  "Ready-mix concrete, C30/37, porous, GWP.70": 0.11,
  "Ready-mix concrete, C25/30, non-porous, GWP.70": 0.08,
  "Ready-mix concrete, C30/37, non-porous, GWP.70": 0.09,
};

export default function getEmission(material) {
  const emissionFactor = emission[material] ? emission[material] : 0;
  return emissionFactor;
}
